uecode/qpush-bundle

src/DependencyInjection/Configuration.php, src/Provider/IronMqProvider.php
The IronMqProvider wasn't using `receive_wait_time` configuration for long polling but it's supported since IronMQ 1.5.2 (https://github.com/iron-io/iron_mq_php/commit/5e61539d0af8294ac39b8441e8813f603ec5b93f).
Update `receive_wait_time` default value for bc as users unaware of this configuration and using IronMQ would now notice a 3 second delay when polling for messages.
May be `iron_mq_php` dependency should be updated to >=1.5.2
=> Enable 'receive_wait_time' configuration parameter for IronMqProvider

.travis.yml, docs/configuration.rst, docs/custom-provider.rst, src/DependencyInjection/Configuration.php, src/DependencyInjection/UecodeQPushExtension.php, src/Provider/CustomProvider.php, src/Resources/config/parameters.yml, tests/MockClient/CustomMockClient.php, tests/Provider/CustomProviderTest.php
Allows users to add their own custom provider for the queue
=> Adding a CustomProvider

composer.json, src/Command/QueueBuildCommand.php, src/Command/QueueDestroyCommand.php, src/Command/QueuePublishCommand.php, src/Command/QueueReceiveCommand.php, src/DependencyInjection/UecodeQPushExtension.php, src/EventListener/RequestListener.php, src/Provider/AbstractProvider.php, src/Provider/AwsProvider.php, src/Provider/IronMqProvider.php, src/UecodeQPushBundle.php, tests/Provider/AbstractProviderTest.php, tests/Provider/AwsProviderTest.php, tests/Provider/IronMqProviderTest.php
This should be a new major version with backward compatible break but it allow the bundle to be use in console application, where including symfony/framework-bundle is an overkill.
=> Remove Symfony framework dependency

composer.json, src/DependencyInjection/UecodeQPushExtension.php
This request updates the dependency for Iron-io/iron_mq package to ~2.0
The DI container was updated to reflect the new class name associated with the package update.
=> Iron mq 2.0

src/Command/QueueReceiveCommand.php, src/DependencyInjection/UecodeQPushExtension.php, src/Provider/AwsProvider.php
- this library now also supports v3 of the aws sdk (while keeping support for v2).
- fixed the QueueReceiveCommand::getContainer() undefined method error.
=> Added support for AWS SDK v3 (v2 still supported) + fixed php error in uecode:qpush:receive command

src/Resources/config/services.yml
`@` characters at the beginning of an unquoted scalar are reserved in
YAML for future use.
=> fix YAML syntax

src/Provider/AwsProvider.php
=> Catch missing queue exeception on queueExists

.travis.yml, composer.json, src/Command/QueueReceiveCommand.php, src/DependencyInjection/UecodeQPushExtension.php, src/EventListener/RequestListener.php, src/Provider/AbstractProvider.php, src/Provider/AwsProvider.php, src/Provider/FileProvider.php, src/Provider/IronMqProvider.php
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #84
| License       | MIT
| Doc PR        | ~
=> Add support of Symfony 3.0

.travis.yml
* fix the Composer cache directory
* run jobs with different Symfony versions only on PHP 5.6
* drop jobs for Symfony versions that reached EOL
* add job for PHP 7
* run code coverage reports only on PHP 7
* disable Xdebug when code coverage reports won't be generated
* finish as soon as possible (when either a mandatory job failed or only
jobs that are allowed to fail are running)
=> improve Travis CI configuration

docs/configuration.rst, docs/file-provider.rst, src/Provider/FileProvider.php
Documentation for the FileProvider was not linked in the official documentation.
Secondly: using the file provider failed when not calling ``php app/console uecode:qpush:build`` before. Using the methods of the Filesystem class is more consistent with the remainder of the code of the FileProvider and also creates parent directories when they are missing.
=> Improvements for FileProvider

.travis.yml, integration_tests/Provider/IronMqProviderTest.php, phpunit.xml.dist, src/EventListener/RequestListener.php, src/Provider/IronMqProvider.php, tests/MockClient/IronMqMockClient.php, tests/Provider/IronMqProviderTest.php
Fixes issue #91 and adds an integration tests which should pickup if the API changes in the future or breaks.
=> Added IronMq Integration test. Updated the MockClient to match the API

src/DependencyInjection/UecodeQPushExtension.php
When a custom (existing) SNS topic name is used in the `queue_name` option, subscription confirmations fail to fire.  
This PR adds an event listener for notifications on the `queue_name` for the AWS providers to correct this.
Should fix #100 and #102
=> Fix for SNS subscription confirmations

src/Resources/config/services.yml
Remove the deprecated warning of not quoting a scalar starting with the "%" indicator character.
=> Fix deprecated scalar starting with the "%" indicator character

src/Provider/AbstractProvider.php, src/Provider/AwsProvider.php, src/Provider/CustomProvider.php, src/Provider/FileProvider.php, src/Provider/IronMqProvider.php, src/Provider/ProviderInterface.php, src/Provider/SyncProvider.php, tests/MockClient/CustomMockClient.php, tests/Provider/CustomProviderTest.php, tests/Provider/SyncProviderTest.php, tests/Provider/TestProvider.php
This allows usage of the library without necessarily using the ```symfony/monolog-bundle```/```symfony/monolog-bridge```. Like for instance in silex apps.
I left the dependency in the composer file the library still requires monolog to be available via symfony DI but this way the logger instance does not have to be the bridge instance but can be any Monolog instance.
=> Monolog: only require basic monolog instance

src/Command/QueueDestroyCommand.php
for https://github.com/easybib/issues/issues/5659
we are using silex 2 and i get an error when i want to run the destroy command
```
uecode:qpush:destroy <name>
[Symfony\Component\Console\Exception\InvalidArgumentException]  
The helper "dialog" is not defined.   
```
found informations here to switch it over. Seems like "dialog" is deprecated 
https://github.com/doctrine/migrations/pull/193
=> command/queueDestroyCommand: replace dialog helper with question helper

src/Provider/AwsProvider.php, tests/Message/NotificationTest.php, tests/MockClient/SnsMockClient.php
Fix for aws/sdk v3 since Aws\Sns\Exception\NotFoundException is no longer available.
In case i had publishing only to queue and then decided to use notifications code fails on creating topic.
Also removed not needed annotation NotificationTest function testConstructor.
=> Fix for topicExists function

src/Provider/AwsProvider.php
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |
The AWS SQS queue with the enabled FIFO option requires the suffix `.fifo` for the queue name. However, the SNS topic (for push notification) doesn't accept the points for the topic name.
This PR fix this bug.
=> Fix invalid SNS topic names with FIFO SQS queues

docs/configuration.rst
Update documentation to reflect that `FIFO` queues are not currently compatible with `push_notifications`.
=> FIFO queues not compatible with push notifications

composer.json, src/Resources/config/parameters.yml, src/Resources/config/services.yml
- Update composer.json
- Add command to services.yml to be able to use it ;)
=> Update composer.json to include version 4.0 for symfony libraries

composer.json
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |
Fix the invalid version of `symfony/config` dependency when the Symfony 4 is used.
=> Fix dependency version of symfony 4
